apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  file:
    matchDirectories:
    - dir: /app/
      recursive: true
    matchPaths:
    - path: /etc/passwd
      action: Block
  process:
    matchPaths:
    - path: /app/wisecow.sh
      action: Allow
    - path: /bin/sh
      action: Allow
    - path: /usr/bin/fortune
      action: Allow
    - path: /usr/games/cowsay
      action: Allow
    - path: /bin/bash
      action: Block
    - path: /usr/bin/bash
      action: Block
    - path: /usr/bin/wget
      action: Block
  action: Allow