name: Cluster Setup - Install cert-manager & ClusterIssuer

on:
  workflow_dispatch:  # Run manually from GitHub Actions UI

jobs:
  setup-cert-manager:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.0'

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_ZONE }} 
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install cert-manager
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -
          helm install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --version v1.14.0 \
            --set installCRDs=true
          
          kubectl wait \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/instance=cert-manager \
            --timeout=120s \
            --namespace=cert-manager

      - name: Apply ClusterIssuer
        run: |
          kubectl apply -f kubernetes/clusterissuer.yml