name: CI/CD Pipeline for Wisecow App

# on:
#   push:
#     branches:
#       - main 

on:
  workflow_dispatch:

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.0'
        
      # - name: Install gke-gcloud-auth-plugin
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_ZONE }} 
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Wisecow application
        run: |
          kubectl apply -f kubernetes/deployment.yml
          kubectl apply -f kubernetes/service.yml
          kubectl apply -f kubernetes/ingress.yml
          kubectl rollout status deployment/wisecow-deployment

      - name: Verify deployment
        run: |
          kubectl get pods -o wide
          kubectl get svc
          kubectl get ingress
