name: CI/CD Pipeline for Wisecow App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t wisecow:latest .

      # 4. Set up Kind cluster
      - name: Set up Kind cluster
        uses: engineerd/setup-kind@v0.6.0
        with:
          version: v0.21.0

      # 5. Load Docker image into Kind cluster
      - name: Load image into Kind
        run: kind load docker-image wisecow:latest

      # 6. Install kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.0'

      # 7. Deploy Wisecow application
      - name: Deploy Wisecow
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl rollout status deployment/wisecow-deployment

      # 8. Test if service is running (optional)
      - name: Check Wisecow service
        run: |
          kubectl get pods -o wide
          kubectl get svc
